# If you modify this file, please also update `RUST_TOOLCHAIN` in `.github/workflows/ci.yml`, the
# `clippy_utils` version in `bevy_lint/Cargo.toml`, and `RUST_TOOLCHAIN` in
# `bevy_lint/src/bin/main.rs`.

[toolchain]
# Writing custom lints requires using nightly Rust. We pin to a specific version of nightly version
# so that builds are reproducible.
channel = "nightly-2024-08-21"
# These components are required to use `rustc` crates.
components = ["rustc-dev", "llvm-tools-preview"]
